=== opengeolab/geocollectorbot/src/schemas/config.schema.json
{
  "$id": "https://raw.githubusercontent.com/opengeolab/geocollectorbot/main/src/schemas/config.schema.json#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "BotConfiguration",
  "type": "object",
  "definitions": {
    "localizedText": {
      "title": "LocalizedText",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "en": {
              "type": "string"
            }
          },
          "additionalProperties": {
            "type": "string"
          },
          "required": ["en"]
        }
      ]
    },

    "flowStep": {
      "title": "FlowStep",
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "question": {
          "$ref": "#/definitions/localizedText"
        },
        "persistAs": {
          "type": "string"
        },
        "nextStepId": {
          "type": "string"
        },
        "config": {
          "title": "FlowStepConfig",
          "oneOf": [
            {
              "title": "TextFlowStepConfig",
              "type": "object",
              "properties": {
                "type": {
                  "const": "text"
                }
              },
              "required": ["type"],
              "additionalProperties": false
            },
            {
              "title": "MultipleChoiceFlowStepConfig",
              "type": "object",
              "properties": {
                "type": {
                  "const": "multipleChoice"
                },
                "options": {
                  "type": "array",
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "text": {
                          "$ref": "#/definitions/localizedText"
                        },
                        "value": {
                          "type": "string"
                        }
                      },
                      "required": ["text", "value"],
                      "additionalProperties": false
                    },
                    "minItems": 1
                  },
                  "minItems": 1
                }
              },
              "required": ["type", "options"],
              "additionalProperties": false
            },
            {
              "title": "LocationFlowStepConfig",
              "type": "object",
              "properties": {
                "type": {
                  "const": "location"
                }
              },
              "required": ["type"],
              "additionalProperties": false
            },
            {
              "title": "SingleMediaFlowStepConfig",
              "type": "object",
              "properties": {
                "type": {
                  "const": "singleMedia"
                },
                "acceptOnly": {
                  "enum": ["photo", "video"]
                }
              },
              "required": ["type"],
              "additionalProperties": false
            },
            {
              "title": "MultipleMediaFlowStepConfig",
              "type": "object",
              "properties": {
                "type": {
                  "const": "multipleMedia"
                },
                "maxItems": {
                  "type": "number"
                },
                "acceptOnly": {
                  "enum": ["photo", "video"]
                }
              },
              "required": ["type"],
              "additionalProperties": false
            }
          ]
        },
        "skippable": {
          "type": "boolean",
          "default": false
        }
      },
      "required": ["id", "question", "config"],
      "additionalProperties": false
    }
  },
  "properties": {
    "$schema": {
      "type": "string"
    },

    "settings": {
      "title": "Settings",
      "type": "object",
      "properties": {
        "includeUserInfoInGetInteractionsApi": {
          "description": "'If set to true, user's data will be returned by the get interactions api'",
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false
    },

    "dataStorage": {
      "title": "DataStorage",
      "oneOf": [
        {
          "title": "PgConfig",
          "type": "object",
          "properties": {
            "type": {
              "const": "postgres"
            },
            "configuration": {
              "type": "object",
              "properties": {
                "connectionString": {
                  "type": "string"
                },
                "interactionsTable": {
                  "type": "string"
                },
                "ssl": {
                  "type": "boolean",
                  "default": false
                }
              },
              "required": ["connectionString", "interactionsTable", "ssl"],
              "additionalProperties": false
            }
          },
          "required": ["type", "configuration"],
          "additionalProperties": false
        }
      ]
    },

    "mediaStorage": {
      "title": "MediaStorage",
      "oneOf": [
        {
          "title": "FsConfig",
          "type": "object",
          "properties": {
            "type": {
              "const": "fileSystem"
            },
            "configuration": {
              "type": "object",
              "properties": {
                "folderPath": {
                  "type": "string"
                }
              },
              "required": ["folderPath"],
              "additionalProperties": false
            }
          },
          "required": ["type", "configuration"],
          "additionalProperties": false
        }
      ]
    },

    "flow": {
      "title": "Flow",
      "type": "object",
      "properties": {
        "firstStepId": {
          "type": "string"
        },
        "steps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/flowStep"
          },
          "minItems": 1
        }
      },
      "required": ["firstStepId", "steps"],
      "additionalProperties": false
    },

    "hooks":{
      "type": "object",
      "properties": {
        "onComplete": {
          "type": "object",
          "properties": {
            "type": {
              "const": "http-post"
            },
            "url": {
              "type": "string"
            }
          },
          "required": ["type", "url"],
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "required": ["dataStorage", "flow"],
  "additionalProperties": false
}

=== opengeolab/geocollectorbot/src/setup/__tests__/mocks/configmap.json
{
  "$schema": "../../../schemas/config.schema.json",
  "settings": {
    "includeUserInfoInGetInteractionsApi": true
  },
  "flow": {
    "firstStepId": "question_1",
    "steps": [
      {
        "id": "question_1",
        "question": "First question",
        "config": {
          "type": "text"
        },
        "nextStepId": "question_2",
        "skippable": true
      },
      {
        "id": "question_2",
        "question": "Second question",
        "config": {
          "type": "text"
        },
        "persistAs": "second_question"
      }
    ]
  },
  "dataStorage": {
    "type": "postgres",
    "configuration": {
      "connectionString": "postgresql://user:password@host:5432/database",
      "interactionsTable": "interactions_table",
      "ssl": false
    }
  },
  "hooks": {
    "onComplete": {
      "type": "http-post",
      "url": "https://www.example.com"
    }
  }
}
